DROP TABLE IF EXISTS Collection;
DROP TABLE IF EXISTS Nft;
DROP TABLE IF EXISTS MintData;
DROP TABLE IF EXISTS OpenRarity;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS MintSaleTransactions;
DROP TABLE IF EXISTS InstarevealCollections;
DROP TABLE IF EXISTS Referrals;